# Generated by Django 5.0.6 on 2025-07-21 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3'), (4, 'Semester 4'), (5, 'Semester 5'), (6, 'Semester 6')])),
                ('subject', models.CharField(max_length=100)),
                ('unit1', models.FileField(blank=True, null=True, upload_to='notes/')),
                ('unit2', models.FileField(blank=True, null=True, upload_to='notes/')),
                ('unit3', models.FileField(blank=True, null=True, upload_to='notes/')),
                ('unit4', models.FileField(blank=True, null=True, upload_to='notes/')),
                ('unit5', models.FileField(blank=True, null=True, upload_to='notes/')),
            ],
        ),
    ]
