# Generated by Django 5.0.6 on 2026-03-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=100)),
                ('post', models.CharField(choices=[('HOD', 'HOD'), ('Founder', 'Founder'), ('Owner', 'Owner'), ('Faculty', 'Faculty')], max_length=50)),
                ('message', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='teachers/')),
            ],
        ),
    ]
