# Generated by Django 5.0.6 on 2026-03-24 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_teachermessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BCAPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('semester', models.CharField(choices=[('Sem 1', 'Sem 1'), ('Sem 2', 'Sem 2'), ('Sem 3', 'Sem 3'), ('Sem 4', 'Sem 4'), ('Sem 5', 'Sem 5'), ('Sem 6', 'Sem 6')], max_length=10)),
                ('year', models.IntegerField()),
                ('paper_file', models.FileField(upload_to='bca_papers/')),
            ],
        ),
    ]
